#Author: Anshuman Verma 
#Email : anshuman@vt.edu
#Date  : Oct 1st, 2016 
#Description : Makefile for BFS, based on Altera Provided Makefiles for sample programs 

# Compiler 
CC  := gcc
CXX := g++

COMPILE: bfs.cpp
	$(CXX) bfs.cpp -o bfs 

.PHONY : all clean emulate full_compile run
